## Contents:
### 1. Importing Packages & File(s)
### 2. Consisitency Checks:
#### 2.1 Data types
#### 2.2 Missing Values
#### 2.3 Duplicated
#### 2.4 Descriptive Statistics

### 1. Importing Packages & File(s):

In [1]:
# Import packages:
import pandas as pd
import numpy as np
import os

In [2]:
# Create string of location
path = '/Users/aegarcia/Desktop/Data analytics/6. Adv Analytics & Dasboard design'
# Import the file accidents.csv
df_car = pd.read_csv(os.path.join(path, '2 Data', 'Original data', 'accidents_new.csv'), index_col = False)

## Consistency Checks:

In [3]:
# First, I want to see how many rows and columns are in the dataset
df_car.shape

(34347, 26)

In [4]:
# Let's see all columns and the first 5 rows
pd.options.display.max_columns = None
df_car.head()

,state,date,weekday,county,time,hour,total_vehicles,persons,fatalitites,route_type,urban_rural,driver_age,driver_gender,driver_license,car_year,car_make,car_model,speed_limit,above_limit,weather,driver_drugs,drug_category,type_drugs,driver_alcohol,alcohol_level (%),death_race
0,Alabama,"January 1, 2020",Wednesday,ELMORE,2:58,2,1,4,3,County Road,Rural,24,Male,Suspended,1997.0,Lexus,ES,45,Yes,Clear,No,No drug,"Tested, No Drugs Found/Negative",Yes,0.294,Black or African American
1,Alabama,"January 2, 2020",Thursday,JEFFERSON,17:18,17,4,6,1,Local Street,Urban,40,Female,Suspended,1993.0,Chevrolet,Corsica,35,No,Rain,Yes,Opioid,FENTANYL,No,0.000,Not a Fatality (not Applicable)
2,Alabama,"January 2, 2020",Thursday,SHELBY,14:55,14,2,2,1,State Highway,Rural,34,Female,Revoked,1995.0,Toyota,Camry,65,Yes,Rain,No,No drug,Test Not Given,No,0.000,White
3,Alabama,"January 3, 2020",Friday,CALHOUN,15:20,15,1,5,1,County Road,Rural,17,Male,Valid,2007.0,Hyundai,Azera,35,Yes,Cloudy,Yes,Depressant,DELTA 9,No,0.000,Not a Fatality (not Applicable)
4,Alabama,"January 4, 2020",Saturday,COOSA,0:45,0,1,1,1,County Road,Rural,47,Female,Valid,2013.0,GMC,Yukon,45,No,Rain,No,No drug,Test Not Given,No,0.000,White

In [5]:
# Let's see all columns and the last 5 rows
pd.options.display.max_columns = None
df_car.tail()

,state,date,weekday,county,time,hour,total_vehicles,persons,fatalitites,route_type,urban_rural,driver_age,driver_gender,driver_license,car_year,car_make,car_model,speed_limit,above_limit,weather,driver_drugs,drug_category,type_drugs,driver_alcohol,alcohol_level (%),death_race
34342,Wyoming,"December 12, 2020",Saturday,LARAMIE,16:36,16,2,2,1,County Road,Rural,62,Male,Valid,2012.0,Ford,F-250,45,No,Snow,No,No drug,Test Not Given,No,0.0,Not a Fatality (not Applicable)
34343,Wyoming,"December 18, 2020",Friday,LINCOLN,18:6,18,3,8,2,U.S. Highway,Rural,31,Female,Valid,2002.0,Dodge,Ram,65,No,Clear,No,No drug,Test Not Given,No,0.0,Not a Fatality (not Applicable)
34344,Wyoming,"December 11, 2020",Friday,FREMONT,17:30,17,3,9,1,State Highway,Rural,67,Male,Valid,2004.0,Honda,Accord,55,Yes,Snow,No,No drug,"Tested, No Drugs Found/Negative",No,0.0,North American Indian or Alaska Native
34345,Wyoming,"December 15, 2020",Tuesday,LARAMIE,20:21,20,2,3,1,U.S. Highway,Urban,18,Female,Valid,2000.0,Buick,LeSabre,30,Yes,Clear,Yes,Cannabis,Tetrahydrocannabinols (THC),No,0.0,Not a Fatality (not Applicable)
34346,Wyoming,"December 24, 2020",Thursday,PLATTE,9:25,9,1,2,1,Interstate,Rural,76,Male,Valid,2001.0,Ford,F-250,80,No,Severe Crosswinds,No,No drug,Test Not Given,No,0.0,White

In [6]:
# Now we will check their type and memory usage
df_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34347 entries, 0 to 34346
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   state              34347 non-null  object
 1   date               34347 non-null  object
 2   weekday            34347 non-null  object
 3   county             34347 non-null  object
 4   time               34347 non-null  object
 5   hour               34347 non-null  int64
 6   total_vehicles     34347 non-null  int64
 7   persons            34347 non-null  int64
 8   fatalitites        34347 non-null  int64
 9   route_type         34347 non-null  object
 10  urban_rural        34347 non-null  object
 11  driver_age         34347 non-null  int64
 12  driver_gender      34347 non-null  object
 13  driver_license     34347 non-null  object
 14  car_year           34003 non-null  float64
 15  car_make           34347 non-null  object
 16  car_model          34347 non-null  object
 17  speed_limit        34347 non-null  int64
 18  above_limit        34347 non-null  object
 19  weather            34347 non-null  object
 20  driver_drugs       34347 non-null  object
 21  drug_category      34347 non-null  object
 22  type_drugs         34347 non-null  object
 23  driver_alcohol     34347 non-null  object
 24  alcohol_level (%)  34347 non-null  float64
 25  death_race         34347 non-null  object
dtypes: float64(2), int64(6), object(18)
memory usage: 6.8+ MB

### 2.1 Mixed data types

In [7]:
# Check for mixed types:
for col in df_car.columns.tolist():
  weird = (df_car[[col]].applymap(type) != df_car[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_car[weird]) > 0:
    print (col)

In [8]:
# Change mixed-type variables
df_car['driver_gender'] = df_car['driver_gender'].astype('str')

In [9]:
# Check for mixed types again:
for col in df_car.columns.tolist():
  weird = (df_car[[col]].applymap(type) != df_car[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_car[weird]) > 0:
    print (col)

#### Yay! No mixed-type variables.

### 2.2: Missing Values

In [10]:
# Get counts of missing values per column
df_car.isnull().sum()

state                  0
date                   0
weekday                0
county                 0
time                   0
hour                   0
total_vehicles         0
persons                0
fatalitites            0
route_type             0
urban_rural            0
driver_age             0
driver_gender          0
driver_license         0
car_year             344
car_make               0
car_model              0
speed_limit            0
above_limit            0
weather                0
driver_drugs           0
drug_category          0
type_drugs             0
driver_alcohol         0
alcohol_level (%)      0
death_race             0
dtype: int64

#### I will impute the average of the year.

### 2.3 Duplicates

In [11]:
df_dups = df_car[df_car.duplicated()]
df_dups

Empty DataFrame
Columns: [state, date, weekday, county, time, hour, total_vehicles, persons, fatalitites, route_type, urban_rural, driver_age, driver_gender, driver_license, car_year, car_make, car_model, speed_limit, above_limit, weather, driver_drugs, drug_category, type_drugs, driver_alcohol, alcohol_level (%), death_race]
Index: []

#### There are no duplicate values!

### 2.4: Descriptive Statistics:

In [12]:
df_car.describe()

,hour,total_vehicles,persons,fatalitites,driver_age,car_year,speed_limit,alcohol_level (%)
count,34347.000000,34347.000000,34347.000000,34347.000000,34347.000000,34003.000000,34347.000000,34347.000000
mean,13.219000,1.568754,2.204443,1.087984,41.772586,2008.278387,48.685911,0.035159
std,6.797849,0.783246,1.604276,0.346687,18.355673,7.703945,13.103441,0.078894
min,0.000000,1.000000,1.000000,1.000000,7.000000,1923.000000,10.000000,0.000000
25%,8.000000,1.000000,1.000000,1.000000,26.000000,2003.000000,40.000000,0.000000
50%,14.000000,1.000000,2.000000,1.000000,38.000000,2008.000000,50.000000,0.000000
75%,19.000000,2.000000,3.000000,1.000000,55.000000,2015.000000,55.000000,0.000000
max,23.000000,15.000000,61.000000,8.000000,100.000000,2021.000000,85.000000,0.558000

#### I found strange that there are several observations where the driver's age is below 15 years of age. The minimum is 7. 
##### Also, the alcohol level goes from 0% up to .85% which I find extreme but there are many other observations that have extremely high values of alcohol level.

In [13]:
# These are the observation that have an alcohol level higher than 50%
df_young_drivers = df_car.loc[df_car['driver_age']<=15]
df_young_drivers

,state,date,weekday,county,time,hour,total_vehicles,persons,fatalitites,route_type,urban_rural,driver_age,driver_gender,driver_license,car_year,car_make,car_model,speed_limit,above_limit,weather,driver_drugs,drug_category,type_drugs,driver_alcohol,alcohol_level (%),death_race
564,Alabama,"September 6, 2020",Sunday,RANDOLPH,15:35,15,2,3,1,County Road,Rural,10,Male,Not licensed,NaN,Other,Other,35,No,Clear,No,No drug,Test Not Given,No,0.00,White
838,Alaska,"June 1, 2020",Monday,KENAI PENINSULA,19:56,19,1,1,1,Unknown,Rural,14,Male,Not licensed,1996.0,Polaris,Sportsman,25,Yes,Clear,No,No drug,"Tested, No Drugs Found/Negative",No,0.00,White
862,Alaska,"June 9, 2020",Tuesday,NORTHWEST ARCTIC,23:0,23,1,3,1,Unknown,Rural,15,Female,Not licensed,2019.0,Honda,TRX420 (Rancher),25,Yes,Clear,No,No drug,"Tested, No Drugs Found/Negative",No,0.00,North American Indian or Alaska Native
1048,Arizona,"April 14, 2020",Tuesday,MOHAVE,0:15,0,2,1,1,Unknown,Urban,15,Male,Not licensed,2004.0,Honda,CRF150,25,Yes,Clear,No,No drug,Test Not Given,No,0.00,Other Race
1194,Arizona,"June 15, 2020",Monday,MARICOPA,2:29,2,1,4,1,Interstate,Urban,15,Male,Not licensed,2005.0,Chevrolet,Tahoe,40,No,Clear,No,No drug,Test Not Given,Yes,0.05,Not a Fatality (not Applicable)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33084,Washington,"June 13, 2020",Saturday,WALLA WALLA,12:20,12,1,3,1,County Road,Rural,14,Female,Not licensed,2010.0,Polaris,Ranger,50,No,Clear,No,No drug,Test Not Given,No,0.00,Not a Fatality (not Applicable)
33132,Washington,"July 14, 2020",Tuesday,YAKIMA,16:40,16,2,3,2,County Road,Rural,14,Male,Not licensed,2005.0,Polaris,Phoenix,45,No,Clear,No,No drug,Negative,No,0.00,Other Race
33738,Wisconsin,"March 30, 2020",Monday,WAUSHARA,2:34,2,1,1,1,County Road,Rural,15,Female,Valid,2002.0,Toyota,Camry,55,No,Clear,No,No drug,Reported as Unknown if Tested for Drugs,No,0.00,Unknown
34202,Wisconsin,"August 17, 2020",Monday,MILWAUKEE,13:40,13,3,2,1,Local Street,Urban,14,Male,Not licensed,2009.0,Acura,MDX,25,No,Cloudy,No,No drug,Reported as Unknown if Tested for Drugs,No,0.00,Not a Fatality (not Applicable)
34221,Wisconsin,"August 27, 2020",Thursday,BARRON,12:45,12,1,4,1,Local Street,Rural,13,Female,Not licensed,2019.0,Polaris,Ranger,30,Yes,Clear,No,No drug,Test Not Given,No,0.00,White

In [14]:
# Counts of drivers by age (younger than 16)
df_young_drivers['driver_age'].value_counts(dropna=False)

15    96
14    37
13    22
12     9
10     5
7      4
11     3
9      2
8      2
Name: driver_age, dtype: int64

### It could be a mistake that there are drivers between 7 and 15 years or age, there are several of them on the news, but I am not able to confirm if this is a mistake or real, so I will leave them as is.

In [15]:
# These are the observation that have an alcohol level higher than 50%
df_high_alcohol = df_car.loc[df_car['alcohol_level (%)']>=0.5]
df_high_alcohol

,state,date,weekday,county,time,hour,total_vehicles,persons,fatalitites,route_type,urban_rural,driver_age,driver_gender,driver_license,car_year,car_make,car_model,speed_limit,above_limit,weather,driver_drugs,drug_category,type_drugs,driver_alcohol,alcohol_level (%),death_race
2950,California,"January 29, 2020",Wednesday,ORANGE,17:7,17,1,2,1,Unknown,Urban,45,Male,Valid,2007.0,Toyota,Sienna,40,No,Clear,No,No drug,"Tested, No Drugs Found/Negative",Yes,0.500,Not a Fatality (not Applicable)
2963,California,"February 2, 2020",Sunday,SANTA CLARA,19:59,19,2,2,1,Unknown,Urban,39,Male,Valid,2012.0,Nissan,Altima,45,Yes,Clear,No,No drug,"Tested, No Drugs Found/Negative",Yes,0.500,Other Asian or Pacific Islander
12496,Indiana,"April 24, 2020",Friday,SPENCER,5:35,5,2,2,1,State Highway,Rural,25,Male,Valid,2004.0,Toyota,Highlander,60,No,Clear,Yes,Positive - Unknown,Positive,Yes,0.500,White
25328,Pennsylvania,"March 14, 2020",Saturday,WASHINGTON,23:43,23,1,1,1,Local Street,Rural,56,Male,Valid,1994.0,Ford,Ranger,25,Yes,Snow,No,No drug,"Tested, No Drugs Found/Negative",Yes,0.558,White
27589,Tennessee,"March 17, 2020",Tuesday,SHELBY,23:32,23,2,3,2,Local Street,Urban,26,Male,Revoked,2002.0,Mitsubishi,Lancer,55,No,Clear,No,No drug,"Tested, No Drugs Found/Negative",Yes,0.539,White
30015,Texas,"June 25, 2020",Thursday,BRAZORIA,10:36,10,2,2,1,State Highway,Urban,57,Male,Suspended,2003.0,Ford,F-150,55,Yes,Rain,Yes,Depressant,BENZODIAZEPINES,Yes,0.500,White
32348,Virginia,"April 17, 2020",Friday,LOUDOUN,13:44,13,1,1,1,County Road,Rural,56,Female,Valid,2006.0,Toyota,PRIUS,35,No,Clear,No,No drug,"Tested, No Drugs Found/Negative",Yes,0.550,White

In [16]:
# Counts
df_high_alcohol['alcohol_level (%)'].value_counts(dropna=False)

0.500    4
0.550    1
0.539    1
0.558    1
Name: alcohol_level (%), dtype: int64

In [17]:
# Export cleaned data
df_car.to_csv(os.path.join(path, '2 Data','Prepared data', 'accidents_clean.csv'))

### The end! :)